meta_name: "Grin.go"
meta_title: "Grin.go - Travel deeper, connect wider"
meta_description: "Uma plataforma feita para locais e viajantes"
meta_image: "banner.png" # should exist in `app/assets/images/`
